---
title: "Resume"
---

## Education

-   PhD University of California Berkeley, Environmental heal Sciences, 2020

-   MPH University of California Berkeley, Environmental Health Sciences, 2011

-   BS University of California, Berkeley, BS Molecular Environmental Biology, 2003

-   AA Merritt Community College, Oakland, General Education, 2000


## Experience

-   **Program on Reproductive Health and the Environment**, University of California, San Francisco, CA. (Nov-2020 - Present)

-   **Women Workers Biomonitoring Collaborative (WWBC)**, University of California, Berkeley, CA. (Feb-2014 - Oct-2020)

-   **Institut National de la Santé et de la Recherche Médicale (INSERM)**, Rennes, France. (Aug-2013 - Feb-2014)

-   **Program on Reproductive Health and the environment**, University of California, San Francisco, CA. (Jun-2010 - Apr-2013)

-   **Biology Scholars Program**, University of California, Berkeley, CA. (Jan-2005 - Aug-2009)

-   **Tiburcio Vasquez Health Center, Inc.** Union City, CA. (Sep-2003 - Dec-2005)


## Honors & Awards

| Time          | Description                                                                                                        |
|:-------------------------------------|:---------------------------------|
| 2021- Present | Science Communication Network Fellowship                                                                           |
| 2021- Present | Co-chair, Environmental influences on Child Health Outcomes (ECHO) diversity supplement                            |
| 2020- Present | Environmental influences on Child Health Outcomes (ECHO) diversity supplement fellowship                           |
| 2020          | 3rd Place, Best Trainee Poster at Mount Sinai Exposomics conference                                                |
| 2019          | Outstanding Graduate Student Instructor Award, UC Berkeley                                                         |
| 2019 -- 2020  | Switzer Environmental Leadership Fellowship; Robert and Patricia Switzer Foundation                                |
| 2016 -- 2020  | Dr. Julia Quint Work and Environment Fellowship, UC Berkeley                                                       |
| 2015 -- 2020  | Targeted Research Training Fellowship T42 National Institute of Occupational Safety and Health (NIOSH OH008429T32) |
| 2017          | Scholarship, American Industrial Hygiene Foundation (AIHF)                                                         |
| 2015 -- 2016  | Scholarship, Hispanic Scholarship Fund (HSF)                                                                       |
| 2010          | Scholarship, Hispanic Community Affairs Council                                                                    |
| 2009 -- 2011  | Scholarship, Sociedad Mexicana Mutualista Morelos, San Francisco                                                   |
